recipe=input()
question=recipe.count("?")
i=0
count=1
ans="YES"
while(i<len(recipe)):
    if(recipe[i]=="?"):
        count=count*26
        if(recipe[i+1]=="?"):
            i=i+2
        else:
            i=i+1
        continue
    elif (recipe[i] == recipe[len(recipe) - i - 1]):
        i=i+1
        continue
    else:
        ans="NO"
        count=0
        break
print(ans)
print(count)